Repository facebookresearch/fairscale, pull requests merged in 2021-04, with the labels that each got.

#563 [feat] remove old MultiProcessPipe
  .circleci/config.yml
  benchmarks/golden_configs/lm_wikitext2.py
  benchmarks/pipe.py
  examples/tutorial_pipe_multiprocess.py
  fairscale/nn/pipe/__init__.py
  fairscale/nn/pipe/multiprocess_pipe.py
  fairscale/nn/pipe/multiprocess_pipeline.py
  tests/nn/model_parallel/test_layers.py
  tests/nn/pipe_process/test_bugs.py
  tests/nn/pipe_process/test_inplace.py
  tests/nn/pipe_process/test_pipe.py
  tests/nn/pipe_process/test_transparency.py
Labels: CLA Signed

#564 [offload] Add support for record_function when using OffloadModel
  benchmarks/experimental/offload.py
  fairscale/experimental/nn/offload.py
Labels: CLA Signed

#572 [fix] Remove folder that has not been added yet
  docs/source/api/index.rst
Labels: CLA Signed

#568 [chore] 0.3.3 release
  CHANGELOG.md
  docs/source/conf.py
  fairscale/__init__.py
Labels: CLA Signed

#570 [test] modify MOE tests to use NCCL
  .circleci/config.yml
  requirements-test.txt
  tests/nn/moe/test_moe_layer.py
Labels: CLA Signed

#565 [FSDP] Add gradient predivide factor to avoid overflow/underflow with large world size
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Labels: CLA Signed

#573 [fix] OSS - enforce cuda parameters for state consolidation if NCCL backend
  fairscale/optim/oss.py
  tests/optim/test_oss.py
Labels: CLA Signed

#575 [test] disable test which has started to become flaky
  tests/nn/pipe_process/test_rpc.py
Labels: CLA Signed

#560 [FSDP] add no_broadcast_optim_state option
  fairscale/nn/data_parallel/fsdp_optim_utils.py
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  tests/nn/data_parallel/test_fsdp.py
  tests/nn/data_parallel/test_fsdp_optimizer_utils.py
Labels: CLA Signed, FSDP

#581 [CI] MNIST download fix
  benchmarks/datasets/mnist.py
Labels: CLA Signed

#582 [OSS/ShardedDDP] making APIs more private
  fairscale/nn/data_parallel/sharded_ddp.py
  fairscale/optim/oss.py
  fairscale/optim/utils.py
  tests/optim/test_oss.py
Labels: CLA Signed

#578 [offload] Add golden data for offload benchmarks.
  .circleci/config.yml
  benchmarks/experimental/offload.py
  benchmarks/golden_configs/lm_wikitext2.py
Labels: CLA Signed

#583 [fix][OSS] Mixed types & proper buckets + no grad_fn is fine
  fairscale/nn/data_parallel/sharded_ddp.py
  fairscale/optim/oss.py
  tests/nn/data_parallel/test_sharded_ddp_features.py
  tests/optim/test_oss.py
Labels: CLA Signed

#579 [FSDP] [feat] Add state_dict_device option
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  stubs/torch/__init__.pyi
  tests/ci_test_list_2.txt
  tests/nn/data_parallel/test_fsdp.py
  tests/nn/data_parallel/test_fsdp_state_dict.py
Labels: CLA Signed

#588 [offload] Fix activation offloading to CPU in FW pass.
  benchmarks/experimental/offload.py
  fairscale/experimental/nn/offload.py
Labels: CLA Signed

#587 [fix][ShardedDDP] Properly handle .eval() mode
  fairscale/nn/data_parallel/sharded_ddp.py
  tests/nn/data_parallel/test_sharded_ddp_features.py
Labels: CLA Signed

#590 [fix] [FSDP] optim state dict should be completely on CPU
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  tests/nn/data_parallel/test_fsdp.py
  tests/nn/data_parallel/test_fsdp_optimizer_utils.py
Labels: CLA Signed

#597 [cleanup] nn.Pipe: deprecate Pipe when torch version >= 1.8.0
  fairscale/nn/pipe/pipe.py
Labels: CLA Signed

#600 split to files
  fairscale/experimental/nn/distributed_pipeline/__init__.py
  fairscale/experimental/nn/distributed_pipeline/data.py
  fairscale/experimental/nn/distributed_pipeline/graph.py
  fairscale/experimental/nn/distributed_pipeline/loss.py
  fairscale/experimental/nn/distributed_pipeline/partition_handler.py
  fairscale/experimental/nn/distributed_pipeline/pipeline.py
  fairscale/experimental/nn/multiprocess_pipe.py
  tests/experimental/nn/test_multiprocess_pipe.py
Labels: CLA Signed

#596 [SDP] Adding a unit test which checks for multiple FW passes on the same block
  tests/nn/data_parallel/test_sharded_ddp_pytorch_parity.py
Labels: CLA Signed

#567 replacing multip-process pipe implementation with more flexible one
  fairscale/experimental/nn/distributed_pipeline/__init__.py
  fairscale/experimental/nn/distributed_pipeline/data.py
  fairscale/experimental/nn/distributed_pipeline/graph.py
  fairscale/experimental/nn/distributed_pipeline/loss.py
  fairscale/experimental/nn/distributed_pipeline/partition_handler.py
  fairscale/experimental/nn/distributed_pipeline/pipeline.py
  fairscale/experimental/nn/multiprocess_pipe.py
  fairscale/nn/pipe/phony.py
  tests/experimental/nn/test_multiprocess_pipe.py
  tests/nn/pipe/test_phony.py
Labels: CLA Signed

#595 [FSDP] use all_gather for 10X OSD consolidation speedup
  fairscale/nn/data_parallel/fsdp_optim_utils.py
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  tests/nn/data_parallel/test_fsdp.py
  tests/nn/data_parallel/test_fsdp_optimizer_utils.py
Labels: CLA Signed, FSDP

#603 [chore] v0.3.4
  CHANGELOG.md
  docs/source/conf.py
  fairscale/__init__.py
Labels: CLA Signed

#606 [fix] [FSDP] Make _get_default_cuda_device more robust to modules without params
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  fairscale/nn/wrap/auto_wrap.py
Labels: CLA Signed

#608 [fix] Revert change that removed the option to run OffloadModel with out activation checkpointing.
  .circleci/config.yml
  benchmarks/experimental/offload.py
  benchmarks/golden_configs/lm_wikitext2.py
  fairscale/experimental/nn/offload.py
  tests/experimental/nn/test_offload.py
Labels: CLA Signed

#611 [chore][SDP] API audit
  fairscale/nn/data_parallel/sharded_ddp.py
Labels: CLA Signed

#614 FSDP: fixing training with freezing weights
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  tests/ci_test_list_1.txt
  tests/nn/data_parallel/test_fsdp_freezing_weights.py
Labels: CLA Signed

#616 [chore] 0.3.5 release
  CHANGELOG.md
  docs/source/conf.py
  fairscale/__init__.py
Labels: CLA Signed

#607 [FSDP] Consolidate cpu_adam optimizer state dict
  benchmarks/experimental/experimental_async_approaches.py
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Labels: FSDP

#618 [chore] OSS - get to 100% coverage
  fairscale/optim/oss.py
Labels: CLA Signed

#619 Changing FSDP init to by pass pg validation
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Labels: CLA Signed

#622 Fixing logging, changing info to debug to avoid clutter
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Labels: CLA Signed

#625 [SDP][Minor] Removing an assert which does not seem always accurate
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  fairscale/nn/data_parallel/sharded_ddp.py
  tests/nn/data_parallel/test_sharded_ddp_features.py
Labels: CLA Signed

#624 [fix] mypy and flaky test
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  tests/nn/data_parallel/test_fsdp_input.py
  tests/nn/data_parallel/test_fsdp_regnet.py
Labels: CLA Signed

#620 [FSDP] relax checking root condition
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  tests/ci_test_list_1.txt
  tests/nn/data_parallel/test_fsdp_multiple_wrapping.py
Labels: CLA Signed

#626 [fix] check before calling _specify_ddp_gpu_num
  fairscale/nn/data_parallel/sharded_ddp.py
  fairscale/utils/parallel.py
Labels: CLA Signed

#621 [fix]: let FSDP handle model with multiple forward pass and checkpoint
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  fairscale/nn/misc/checkpoint_activations.py
  fairscale/nn/misc/misc.py
  fairscale/utils/testing.py
  stubs/torch/nn/modules/module.pyi
  tests/ci_test_list_1.txt
  tests/nn/data_parallel/test_fsdp_freezing_weights.py
  tests/nn/data_parallel/test_fsdp_multiple_forward_checkpoint.py
Labels: CLA Signed

#631 [chore] 0.3.6 release
  CHANGELOG.md
  docs/source/conf.py
  fairscale/__init__.py
  setup.py
Labels: CLA Signed

#632 [chore] Suggest a changelog addition for each PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CLA Signed

#630 [chore] SDP - adding the profiler labels
  fairscale/nn/data_parallel/sharded_ddp.py
Labels: CLA Signed

#629 [chore] Adding some profiling labels to OSS
  fairscale/optim/oss.py
Labels: CLA Signed

#633 [feat] save memory by using bucket buffer only in backward
  CHANGELOG.md
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  fairscale/utils/reduce_scatter_bucketer.py
  tests/ci_test_list_1.txt
  tests/nn/data_parallel/test_fsdp_memory.py
Labels: CLA Signed

#634 [chore] do not build cuda extensions by default
  CHANGELOG.md
  pyproject.toml
  setup.py
Labels: CLA Signed

#615 adding auto graph generation for distributed pipeline
  fairscale/experimental/nn/distributed_pipeline/graph.py
  fairscale/experimental/nn/distributed_pipeline/trace.py
  setup.cfg
  tests/experimental/nn/test_multiprocess_pipe.py
Labels: CLA Signed

#638 [test] improve BN test coverage
  tests/nn/data_parallel/test_fsdp_regnet.py
Labels: CLA Signed

#639 [test][minor] Improving SDP test coverage
  .pre-commit-config.yaml
  fairscale/nn/data_parallel/sharded_ddp.py
  fairscale/optim/utils.py
  tests/nn/data_parallel/test_sharded_ddp_features.py
Labels: CLA Signed

#640 [refactor][minor][sdp] using context-based tempfiles
  tests/nn/data_parallel/test_sharded_ddp_features.py
  tests/nn/data_parallel/test_sharded_ddp_pytorch_parity.py
Labels: CLA Signed

#645 [test] nn.Pipe: add a parity test that also tests with amp
  tests/ci_test_list_1.txt
  tests/nn/pipe/test_parity.py
Labels: CLA Signed
