Repository facebookresearch/fairscale, pull requests merged in 2022-02, with the labels that each got.

#929 [chore] Fix docs build by updating the numpy intersphinx mapping
  docs/source/conf.py
  tests/nn/data_parallel/test_fsdp.py
Labels: CLA Signed, better_eng

#926 [FSDP] Add an arg for FSDP __init__
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
Labels: CLA Signed

#932 [minor] skipping one more flaky test
  fairscale/utils/testing.py
  tests/nn/data_parallel/test_fsdp.py
  tests/optim/test_layerwise_gradient_scaler.py
Labels: CLA Signed

#930 [fix] Add option to wrap root module in auto_wrap
  fairscale/nn/wrap/auto_wrap.py
  tests/nn/wrap/test_wrap.py
Labels: CLA Signed, FSDP

#935 Update CHANGELOG.md
  CHANGELOG.md
Labels: CLA Signed

#765 [benchmarks] Add benchmarks for FSDP
  .circleci/config.yml
  benchmarks/fsdp.py
  benchmarks/golden_configs/lm_wikitext2.py
  tests/nn/data_parallel/test_fsdp.py
Labels: CLA Signed, FSDP + SSD offload

#938 [chore]Fix typo in skipped test to prevent an explicit failure
  tests/nn/data_parallel/test_fsdp.py
Labels: CLA Signed

#936 [fix][FSDP] Add support for saving optimizer state with expert replication
  CHANGELOG.md
  fairscale/nn/data_parallel/fully_sharded_data_parallel.py
  tests/nn/data_parallel/test_fsdp.py
  tests/nn/data_parallel/test_fsdp_optimizer_utils.py
Labels: CLA Signed
